# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 22:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('writer', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 4, 21, 22, 1, 3, 213362, tzinfo=utc), verbose_name='date published')),
                ('short_text', models.TextField()),
                ('text', models.TextField(default='')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='/news/media/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Article')),
            ],
        ),
    ]
