# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 21:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 25, 21, 56, 34, 65692, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='articleimages',
            name='image',
            field=models.TextField(),
        ),
    ]
