# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 08:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160425_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 26, 8, 1, 42, 931123, tzinfo=utc), verbose_name='date published'),
        ),
    ]
